<?php

return [
    'full-width-fields' => ['table-related', 'table', 'html-page', 'json'],
    'global_currency' => 'USD',
    'default_language' => 'en',
    'hierarchies' => ['Category'],
    'countries' => [],
    'web_order_prefix' => env('AMPLIFY_WEB_ORDER_PREFIX', 'AMP'),
    'nxt_available_web_order_number' => '0000001',
    'is_elfinder_drag_and_drop' => true,
    'date_time_format' => 'Y-m-d H:i:s',
    'date_format' => 'd M Y',
    'default_reorder_limit' => 10,
    'navbar_brand' => 'img/Amplify Logo 280 tagline.png',
    'footer_image' => 'img/Powered by EasyAsk.png',
    'suppress_exception' => env('AMPLIFY_SUPPRESS_EXCEPTION', true),
    'length_options' => '10,25,50,100,500',
    'color_scheme' => 'orange',
    'force_password_reset_enabled' => true,
    'recaptcha_type' => 'math',
    'enable_quick_list' => true,
    'enable_multi_customer_manage' => true,
    'enable_guest_pricing' => false,
    'shop_page_prefix' => env('AMPLIFY_SHOP_PAGE_PREFIX', 'shop'),
    'is_permission_system_enabled' => (bool) env('AMPLIFY_PERMISSION_SYSTEM_ENABLED', false),
    'excluded_redirect_urls' => [
        'login',
        'registration',
        'forgot-password',
        'force-reset-password',
        'verify-email',
        'confirm-password',
        'favourites/create',
        'fetch-products',
        'messages/create',
        'home',
        'get/carts',
    ],
    'contact_import_default_password' => env('AMPLIFY_CONTACT_DEFAULT_PASSWORD', 'amplify2024'),
];
