<?php

return [

    /**
     * Add the rule class with key for booting your rule class
     */
    'order-rules' => [
        'sub-total-rule' => \Amplify\System\OrderRule\Rules\SubTotalRule::class,
        'forbidden-product-rule' => \Amplify\System\OrderRule\Rules\ForbiddenProductRule::class,
        'cart-item-count-rule' => \Amplify\System\OrderRule\Rules\CartItemCountRule::class,
    ],

    /**
     * Add the rule label with rule key for front-end rendering.
     */
    'order-rules-label' => [
        'sub-total-rule' => 'Approval on Order Total Amount',
        'forbidden-product-rule' => 'Approval on Restricted Product',
        'cart-item-count-rule' => 'Approval on Max Item in Single Cart',
    ],

    'order-rule-approval-status' => [
        'pending' => 'Pending',
        'passed' => 'Passed',
        'failed' => 'Failed',
    ],

    'favorite_list_type' => [
        'global' => 'Global',
        'personal' => 'Personal',
        'quick-list' => 'Quick List',
    ],

    /**
     * show a
     *
     * @see config/filesystems.php for name formats
     *
     * name -> disk name
     * label -> Displayable title
     */
    'available_disks' => [
        [
            'name' => 'uploads',
            'label' => 'Uploads',
        ],
        [
            'name' => 'logs',
            'label' => 'Log',
        ],
    ],

    'available_locales' => [],

    'date_formats' => [
        'Y-m-d',
        'd-m-Y',
        'Y/m/d',
        'd/m/Y',
        'd M, y',
        'd M Y',
        'm-d-y',
    ],
    // @see https://momentjs.com/docs/#/displaying/
    'moment_date_formats' => [
        'Y-m-d' => 'YYYY-MM-DD',
        'd-m-Y' => 'DD-MM-YYYY',
        'Y/m/d' => 'YYYY/MM/DD',
        'd/m/Y' => 'DD/MM/YYYY',
        'd M, y' => 'DD MMM, YY',
        'd M Y' => 'DD MMM YYYY',
        'm-d-y' => 'MM-DD-YY',
    ],

    'date_time_formats' => [
        'd M Y, H:i',

        'Y-m-d H:i:s',
        'Y-m-d h:i:s',
        'Y-m-d H:i A',
        'Y-m-d h:i',
        'Y-m-d',

        'd-m-Y H:i:s',
        'd-m-Y h:i:s A',
        'd-m-Y H:i',
        'd-m-Y h:i',
        'd-m-Y',
        'd-m-Y h:i:s',

        'Y/m/d H:i:s',
        'Y/m/d h:i:s A',
        'Y/m/d H:i',
        'Y/m/d h:i',
        'Y/m/d',

        'Y/m/d h:i:s',
        'd/m/Y h:i:s',
        'd/m/Y H:i:s',
        'd/m/Y h:i:s A',
        'd/m/Y H:i',
        'd/m/Y h:i',
        'd/m/Y',

        'd M, Y h:i:s',
        'd M, Y H:i:s',
        'd M, Y h:i:s A',
        'd M, Y H:i',
        'd M, Y h:i',
        'd M, Y',

        'm-d-y h:i A',
    ],

    'timezone' => [
        'UTC' => ['offset' => 'GMT-00:00', 'name' => 'UTC'],
        'America/Adak' => ['offset' => 'GMT-10:00', 'name' => 'America/Adak'],
        'America/Atka' => ['offset' => 'GMT-10:00', 'name' => 'America/Atka'],
        'America/Anchorage' => ['offset' => 'GMT-09:00', 'name' => 'America/Anchorage'],
        'America/Juneau' => ['offset' => 'GMT-09:00', 'name' => 'America/Juneau'],
        'America/Nome' => ['offset' => 'GMT-09:00', 'name' => 'America/Nome'],
        'America/Yakutat' => ['offset' => 'GMT-09:00', 'name' => 'America/Yakutat'],
        'America/Dawson' => ['offset' => 'GMT-08:00', 'name' => 'America/Dawson'],
        'America/Ensenada' => ['offset' => 'GMT-08:00', 'name' => 'America/Ensenada'],
        'America/Los_Angeles' => ['offset' => 'GMT-08:00', 'name' => 'America/Los_Angeles'],
        'America/Tijuana' => ['offset' => 'GMT-08:00', 'name' => 'America/Tijuana'],
        'America/Vancouver' => ['offset' => 'GMT-08:00', 'name' => 'America/Vancouver'],
        'America/Whitehorse' => ['offset' => 'GMT-08:00', 'name' => 'America/Whitehorse'],
        'Canada/Pacific' => ['offset' => 'GMT-08:00', 'name' => 'Canada/Pacific'],
        'Canada/Yukon' => ['offset' => 'GMT-08:00', 'name' => 'Canada/Yukon'],
        'Mexico/BajaNorte' => ['offset' => 'GMT-08:00', 'name' => 'Mexico/BajaNorte'],
        'America/Boise' => ['offset' => 'GMT-07:00', 'name' => 'America/Boise'],
        'America/Cambridge_Bay' => ['offset' => 'GMT-07:00', 'name' => 'America/Cambridge_Bay'],
        'America/Chihuahua' => ['offset' => 'GMT-07:00', 'name' => 'America/Chihuahua'],
        'America/Dawson_Creek' => ['offset' => 'GMT-07:00', 'name' => 'America/Dawson_Creek'],
        'America/Denver' => ['offset' => 'GMT-07:00', 'name' => 'America/Denver'],
        'America/Edmonton' => ['offset' => 'GMT-07:00', 'name' => 'America/Edmonton'],
        'America/Hermosillo' => ['offset' => 'GMT-07:00', 'name' => 'America/Hermosillo'],
        'America/Inuvik' => ['offset' => 'GMT-07:00', 'name' => 'America/Inuvik'],
        'America/Mazatlan' => ['offset' => 'GMT-07:00', 'name' => 'America/Mazatlan'],
        'America/Phoenix' => ['offset' => 'GMT-07:00', 'name' => 'America/Phoenix'],
        'America/Shiprock' => ['offset' => 'GMT-07:00', 'name' => 'America/Shiprock'],
        'America/Yellowknife' => ['offset' => 'GMT-07:00', 'name' => 'America/Yellowknife'],
        'Canada/Mountain' => ['offset' => 'GMT-07:00', 'name' => 'Canada/Mountain'],
        'Mexico/BajaSur' => ['offset' => 'GMT-07:00', 'name' => 'Mexico/BajaSur'],
        'America/Belize' => ['offset' => 'GMT-06:00', 'name' => 'America/Belize'],
        'America/Cancun' => ['offset' => 'GMT-06:00', 'name' => 'America/Cancun'],
        'America/Chicago' => ['offset' => 'GMT-06:00', 'name' => 'America/Chicago'],
        'America/Costa_Rica' => ['offset' => 'GMT-06:00', 'name' => 'America/Costa_Rica'],
        'America/El_Salvador' => ['offset' => 'GMT-06:00', 'name' => 'America/El_Salvador'],
        'America/Guatemala' => ['offset' => 'GMT-06:00', 'name' => 'America/Guatemala'],
        'America/Knox_IN' => ['offset' => 'GMT-06:00', 'name' => 'America/Knox_IN'],
        'America/Managua' => ['offset' => 'GMT-06:00', 'name' => 'America/Managua'],
        'America/Menominee' => ['offset' => 'GMT-06:00', 'name' => 'America/Menominee'],
        'America/Merida' => ['offset' => 'GMT-06:00', 'name' => 'America/Merida'],
        'America/Mexico_City' => ['offset' => 'GMT-06:00', 'name' => 'America/Mexico_City'],
        'America/Monterrey' => ['offset' => 'GMT-06:00', 'name' => 'America/Monterrey'],
        'America/Rainy_River' => ['offset' => 'GMT-06:00', 'name' => 'America/Rainy_River'],
        'America/Rankin_Inlet' => ['offset' => 'GMT-06:00', 'name' => 'America/Rankin_Inlet'],
        'America/Regina' => ['offset' => 'GMT-06:00', 'name' => 'America/Regina'],
        'America/Swift_Current' => ['offset' => 'GMT-06:00', 'name' => 'America/Swift_Current'],
        'America/Tegucigalpa' => ['offset' => 'GMT-06:00', 'name' => 'America/Tegucigalpa'],
        'America/Winnipeg' => ['offset' => 'GMT-06:00', 'name' => 'America/Winnipeg'],
        'Canada/Central' => ['offset' => 'GMT-06:00', 'name' => 'Canada/Central'],
        'Canada/East-Saskatchewan' => ['offset' => 'GMT-06:00', 'name' => 'Canada/East-Saskatchewan'],
        'Canada/Saskatchewan' => ['offset' => 'GMT-06:00', 'name' => 'Canada/Saskatchewan'],
        'Chile/EasterIsland' => ['offset' => 'GMT-06:00', 'name' => 'Chile/EasterIsland'],
        'Mexico/General' => ['offset' => 'GMT-06:00', 'name' => 'Mexico/General'],
        'America/Atikokan' => ['offset' => 'GMT-05:00', 'name' => 'America/Atikokan'],
        'America/Bogota' => ['offset' => 'GMT-05:00', 'name' => 'America/Bogota'],
        'America/Cayman' => ['offset' => 'GMT-05:00', 'name' => 'America/Cayman'],
        'America/Coral_Harbour' => ['offset' => 'GMT-05:00', 'name' => 'America/Coral_Harbour'],
        'America/Detroit' => ['offset' => 'GMT-05:00', 'name' => 'America/Detroit'],
        'America/Fort_Wayne' => ['offset' => 'GMT-05:00', 'name' => 'America/Fort_Wayne'],
        'America/Grand_Turk' => ['offset' => 'GMT-05:00', 'name' => 'America/Grand_Turk'],
        'America/Guayaquil' => ['offset' => 'GMT-05:00', 'name' => 'America/Guayaquil'],
        'America/Havana' => ['offset' => 'GMT-05:00', 'name' => 'America/Havana'],
        'America/Indianapolis' => ['offset' => 'GMT-05:00', 'name' => 'America/Indianapolis'],
        'America/Iqaluit' => ['offset' => 'GMT-05:00', 'name' => 'America/Iqaluit'],
        'America/Jamaica' => ['offset' => 'GMT-05:00', 'name' => 'America/Jamaica'],
        'America/Lima' => ['offset' => 'GMT-05:00', 'name' => 'America/Lima'],
        'America/Louisville' => ['offset' => 'GMT-05:00', 'name' => 'America/Louisville'],
        'America/Montreal' => ['offset' => 'GMT-05:00', 'name' => 'America/Montreal'],
        'America/Nassau' => ['offset' => 'GMT-05:00', 'name' => 'America/Nassau'],
        'America/New_York' => ['offset' => 'GMT-05:00', 'name' => 'America/New_York'],
        'America/Nipigon' => ['offset' => 'GMT-05:00', 'name' => 'America/Nipigon'],
        'America/Panama' => ['offset' => 'GMT-05:00', 'name' => 'America/Panama'],
        'America/Pangnirtung' => ['offset' => 'GMT-05:00', 'name' => 'America/Pangnirtung'],
        'America/Port-au-Prince' => ['offset' => 'GMT-05:00', 'name' => 'America/Port-au-Prince'],
        'America/Resolute' => ['offset' => 'GMT-05:00', 'name' => 'America/Resolute'],
        'America/Thunder_Bay' => ['offset' => 'GMT-05:00', 'name' => 'America/Thunder_Bay'],
        'America/Toronto' => ['offset' => 'GMT-05:00', 'name' => 'America/Toronto'],
        'Canada/Eastern' => ['offset' => 'GMT-05:00', 'name' => 'Canada/Eastern'],
        'America/Caracas' => ['offset' => 'GMT-04-30', 'name' => 'America/Caracas'],
        'America/Anguilla' => ['offset' => 'GMT-04:00', 'name' => 'America/Anguilla'],
        'America/Antigua' => ['offset' => 'GMT-04:00', 'name' => 'America/Antigua'],
        'America/Aruba' => ['offset' => 'GMT-04:00', 'name' => 'America/Aruba'],
        'America/Asuncion' => ['offset' => 'GMT-04:00', 'name' => 'America/Asuncion'],
        'America/Barbados' => ['offset' => 'GMT-04:00', 'name' => 'America/Barbados'],
        'America/Blanc-Sablon' => ['offset' => 'GMT-04:00', 'name' => 'America/Blanc-Sablon'],
        'America/Boa_Vista' => ['offset' => 'GMT-04:00', 'name' => 'America/Boa_Vista'],
        'America/Campo_Grande' => ['offset' => 'GMT-04:00', 'name' => 'America/Campo_Grande'],
        'America/Cuiaba' => ['offset' => 'GMT-04:00', 'name' => 'America/Cuiaba'],
        'America/Curacao' => ['offset' => 'GMT-04:00', 'name' => 'America/Curacao'],
        'America/Dominica' => ['offset' => 'GMT-04:00', 'name' => 'America/Dominica'],
        'America/Eirunepe' => ['offset' => 'GMT-04:00', 'name' => 'America/Eirunepe'],
        'America/Glace_Bay' => ['offset' => 'GMT-04:00', 'name' => 'America/Glace_Bay'],
        'America/Goose_Bay' => ['offset' => 'GMT-04:00', 'name' => 'America/Goose_Bay'],
        'America/Grenada' => ['offset' => 'GMT-04:00', 'name' => 'America/Grenada'],
        'America/Guadeloupe' => ['offset' => 'GMT-04:00', 'name' => 'America/Guadeloupe'],
        'America/Guyana' => ['offset' => 'GMT-04:00', 'name' => 'America/Guyana'],
        'America/Halifax' => ['offset' => 'GMT-04:00', 'name' => 'America/Halifax'],
        'America/La_Paz' => ['offset' => 'GMT-04:00', 'name' => 'America/La_Paz'],
        'America/Manaus' => ['offset' => 'GMT-04:00', 'name' => 'America/Manaus'],
        'America/Marigot' => ['offset' => 'GMT-04:00', 'name' => 'America/Marigot'],
        'America/Martinique' => ['offset' => 'GMT-04:00', 'name' => 'America/Martinique'],
        'America/Moncton' => ['offset' => 'GMT-04:00', 'name' => 'America/Moncton'],
        'America/Montserrat' => ['offset' => 'GMT-04:00', 'name' => 'America/Montserrat'],
        'America/Port_of_Spain' => ['offset' => 'GMT-04:00', 'name' => 'America/Port_of_Spain'],
        'America/Porto_Acre' => ['offset' => 'GMT-04:00', 'name' => 'America/Porto_Acre'],
        'America/Porto_Velho' => ['offset' => 'GMT-04:00', 'name' => 'America/Porto_Velho'],
        'America/Puerto_Rico' => ['offset' => 'GMT-04:00', 'name' => 'America/Puerto_Rico'],
        'America/Rio_Branco' => ['offset' => 'GMT-04:00', 'name' => 'America/Rio_Branco'],
        'America/Santiago' => ['offset' => 'GMT-04:00', 'name' => 'America/Santiago'],
        'America/Santo_Domingo' => ['offset' => 'GMT-04:00', 'name' => 'America/Santo_Domingo'],
        'America/St_Barthelemy' => ['offset' => 'GMT-04:00', 'name' => 'America/St_Barthelemy'],
        'America/St_Kitts' => ['offset' => 'GMT-04:00', 'name' => 'America/St_Kitts'],
        'America/St_Lucia' => ['offset' => 'GMT-04:00', 'name' => 'America/St_Lucia'],
        'America/St_Thomas' => ['offset' => 'GMT-04:00', 'name' => 'America/St_Thomas'],
        'America/St_Vincent' => ['offset' => 'GMT-04:00', 'name' => 'America/St_Vincent'],
        'America/Thule' => ['offset' => 'GMT-04:00', 'name' => 'America/Thule'],
        'America/Tortola' => ['offset' => 'GMT-04:00', 'name' => 'America/Tortola'],
        'America/Virgin' => ['offset' => 'GMT-04:00', 'name' => 'America/Virgin'],
        'Antarctica/Palmer' => ['offset' => 'GMT-04:00', 'name' => 'Antarctica/Palmer'],
        'Atlantic/Bermuda' => ['offset' => 'GMT-04:00', 'name' => 'Atlantic/Bermuda'],
        'Atlantic/Stanley' => ['offset' => 'GMT-04:00', 'name' => 'Atlantic/Stanley'],
        'Brazil/Acre' => ['offset' => 'GMT-04:00', 'name' => 'Brazil/Acre'],
        'Brazil/West' => ['offset' => 'GMT-04:00', 'name' => 'Brazil/West'],
        'Canada/Atlantic' => ['offset' => 'GMT-04:00', 'name' => 'Canada/Atlantic'],
        'Chile/Continental' => ['offset' => 'GMT-04:00', 'name' => 'Chile/Continental'],
        'America/St_Johns' => ['offset' => 'GMT-03-30', 'name' => 'America/St_Johns'],
        'Canada/Newfoundland' => ['offset' => 'GMT-03-30', 'name' => 'Canada/Newfoundland'],
        'America/Araguaina' => ['offset' => 'GMT-03:00', 'name' => 'America/Araguaina'],
        'America/Bahia' => ['offset' => 'GMT-03:00', 'name' => 'America/Bahia'],
        'America/Belem' => ['offset' => 'GMT-03:00', 'name' => 'America/Belem'],
        'America/Buenos_Aires' => ['offset' => 'GMT-03:00', 'name' => 'America/Buenos_Aires'],
        'America/Catamarca' => ['offset' => 'GMT-03:00', 'name' => 'America/Catamarca'],
        'America/Cayenne' => ['offset' => 'GMT-03:00', 'name' => 'America/Cayenne'],
        'America/Cordoba' => ['offset' => 'GMT-03:00', 'name' => 'America/Cordoba'],
        'America/Fortaleza' => ['offset' => 'GMT-03:00', 'name' => 'America/Fortaleza'],
        'America/Godthab' => ['offset' => 'GMT-03:00', 'name' => 'America/Godthab'],
        'America/Jujuy' => ['offset' => 'GMT-03:00', 'name' => 'America/Jujuy'],
        'America/Maceio' => ['offset' => 'GMT-03:00', 'name' => 'America/Maceio'],
        'America/Mendoza' => ['offset' => 'GMT-03:00', 'name' => 'America/Mendoza'],
        'America/Miquelon' => ['offset' => 'GMT-03:00', 'name' => 'America/Miquelon'],
        'America/Montevideo' => ['offset' => 'GMT-03:00', 'name' => 'America/Montevideo'],
        'America/Paramaribo' => ['offset' => 'GMT-03:00', 'name' => 'America/Paramaribo'],
        'America/Recife' => ['offset' => 'GMT-03:00', 'name' => 'America/Recife'],
        'America/Rosario' => ['offset' => 'GMT-03:00', 'name' => 'America/Rosario'],
        'America/Santarem' => ['offset' => 'GMT-03:00', 'name' => 'America/Santarem'],
        'America/Sao_Paulo' => ['offset' => 'GMT-03:00', 'name' => 'America/Sao_Paulo'],
        'Antarctica/Rothera' => ['offset' => 'GMT-03:00', 'name' => 'Antarctica/Rothera'],
        'Brazil/East' => ['offset' => 'GMT-03:00', 'name' => 'Brazil/East'],
        'America/Noronha' => ['offset' => 'GMT-02:00', 'name' => 'America/Noronha'],
        'Atlantic/South_Georgia' => ['offset' => 'GMT-02:00', 'name' => 'Atlantic/South_Georgia'],
        'Brazil/DeNoronha' => ['offset' => 'GMT-02:00', 'name' => 'Brazil/DeNoronha'],
        'America/Scoresbysund' => ['offset' => 'GMT-01:00', 'name' => 'America/Scoresbysund'],
        'Atlantic/Azores' => ['offset' => 'GMT-01:00', 'name' => 'Atlantic/Azores'],
        'Atlantic/Cape_Verde' => ['offset' => 'GMT-01:00', 'name' => 'Atlantic/Cape_Verde'],
        'Africa/Abidjan' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Abidjan'],
        'Africa/Accra' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Accra'],
        'Africa/Bamako' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Bamako'],
        'Africa/Banjul' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Banjul'],
        'Africa/Bissau' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Bissau'],
        'Africa/Casablanca' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Casablanca'],
        'Africa/Conakry' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Conakry'],
        'Africa/Dakar' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Dakar'],
        'Africa/El_Aaiun' => ['offset' => 'GMT+00:00', 'name' => 'Africa/El_Aaiun'],
        'Africa/Freetown' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Freetown'],
        'Africa/Lome' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Lome'],
        'Africa/Monrovia' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Monrovia'],
        'Africa/Nouakchott' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Nouakchott'],
        'Africa/Ouagadougou' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Ouagadougou'],
        'Africa/Sao_Tome' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Sao_Tome'],
        'Africa/Timbuktu' => ['offset' => 'GMT+00:00', 'name' => 'Africa/Timbuktu'],
        'America/Danmarkshavn' => ['offset' => 'GMT+00:00', 'name' => 'America/Danmarkshavn'],
        'Atlantic/Canary' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/Canary'],
        'Atlantic/Faeroe' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/Faeroe'],
        'Atlantic/Faroe' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/Faroe'],
        'Atlantic/Madeira' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/Madeira'],
        'Atlantic/Reykjavik' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/Reykjavik'],
        'Atlantic/St_Helena' => ['offset' => 'GMT+00:00', 'name' => 'Atlantic/St_Helena'],
        'Europe/Belfast' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Belfast'],
        'Europe/Dublin' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Dublin'],
        'Europe/Guernsey' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Guernsey'],
        'Europe/Isle_of_Man' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Isle_of_Man'],
        'Europe/Jersey' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Jersey'],
        'Europe/Lisbon' => ['offset' => 'GMT+00:00', 'name' => 'Europe/Lisbon'],
        'Europe/London' => ['offset' => 'GMT+00:00', 'name' => 'Europe/London'],
        'Africa/Algiers' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Algiers'],
        'Africa/Bangui' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Bangui'],
        'Africa/Brazzaville' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Brazzaville'],
        'Africa/Ceuta' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Ceuta'],
        'Africa/Douala' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Douala'],
        'Africa/Kinshasa' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Kinshasa'],
        'Africa/Lagos' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Lagos'],
        'Africa/Libreville' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Libreville'],
        'Africa/Luanda' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Luanda'],
        'Africa/Malabo' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Malabo'],
        'Africa/Ndjamena' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Ndjamena'],
        'Africa/Niamey' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Niamey'],
        'Africa/Porto-Novo' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Porto-Novo'],
        'Africa/Tunis' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Tunis'],
        'Africa/Windhoek' => ['offset' => 'GMT+01:00', 'name' => 'Africa/Windhoek'],
        'Arctic/Longyearbyen' => ['offset' => 'GMT+01:00', 'name' => 'Arctic/Longyearbyen'],
        'Atlantic/Jan_Mayen' => ['offset' => 'GMT+01:00', 'name' => 'Atlantic/Jan_Mayen'],
        'Europe/Amsterdam' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Amsterdam'],
        'Europe/Andorra' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Andorra'],
        'Europe/Belgrade' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Belgrade'],
        'Europe/Berlin' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Berlin'],
        'Europe/Bratislava' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Bratislava'],
        'Europe/Brussels' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Brussels'],
        'Europe/Budapest' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Budapest'],
        'Europe/Copenhagen' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Copenhagen'],
        'Europe/Gibraltar' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Gibraltar'],
        'Europe/Ljubljana' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Ljubljana'],
        'Europe/Luxembourg' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Luxembourg'],
        'Europe/Madrid' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Madrid'],
        'Europe/Malta' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Malta'],
        'Europe/Monaco' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Monaco'],
        'Europe/Oslo' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Oslo'],
        'Europe/Paris' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Paris'],
        'Europe/Podgorica' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Podgorica'],
        'Europe/Prague' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Prague'],
        'Europe/Rome' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Rome'],
        'Europe/San_Marino' => ['offset' => 'GMT+01:00', 'name' => 'Europe/San_Marino'],
        'Europe/Sarajevo' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Sarajevo'],
        'Europe/Skopje' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Skopje'],
        'Europe/Stockholm' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Stockholm'],
        'Europe/Tirane' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Tirane'],
        'Europe/Vaduz' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Vaduz'],
        'Europe/Vatican' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Vatican'],
        'Europe/Vienna' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Vienna'],
        'Europe/Warsaw' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Warsaw'],
        'Europe/Zagreb' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Zagreb'],
        'Europe/Zurich' => ['offset' => 'GMT+01:00', 'name' => 'Europe/Zurich'],
        'Africa/Blantyre' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Blantyre'],
        'Africa/Bujumbura' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Bujumbura'],
        'Africa/Cairo' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Cairo'],
        'Africa/Gaborone' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Gaborone'],
        'Africa/Harare' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Harare'],
        'Africa/Johannesburg' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Johannesburg'],
        'Africa/Kigali' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Kigali'],
        'Africa/Lubumbashi' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Lubumbashi'],
        'Africa/Lusaka' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Lusaka'],
        'Africa/Maputo' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Maputo'],
        'Africa/Maseru' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Maseru'],
        'Africa/Mbabane' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Mbabane'],
        'Africa/Tripoli' => ['offset' => 'GMT+02:00', 'name' => 'Africa/Tripoli'],
        'Asia/Amman' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Amman'],
        'Asia/Beirut' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Beirut'],
        'Asia/Damascus' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Damascus'],
        'Asia/Gaza' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Gaza'],
        'Asia/Istanbul' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Istanbul'],
        'Asia/Jerusalem' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Jerusalem'],
        'Asia/Nicosia' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Nicosia'],
        'Asia/Tel_Aviv' => ['offset' => 'GMT+02:00', 'name' => 'Asia/Tel_Aviv'],
        'Europe/Athens' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Athens'],
        'Europe/Bucharest' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Bucharest'],
        'Europe/Chisinau' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Chisinau'],
        'Europe/Helsinki' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Helsinki'],
        'Europe/Istanbul' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Istanbul'],
        'Europe/Kaliningrad' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Kaliningrad'],
        'Europe/Kiev' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Kiev'],
        'Europe/Mariehamn' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Mariehamn'],
        'Europe/Minsk' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Minsk'],
        'Europe/Nicosia' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Nicosia'],
        'Europe/Riga' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Riga'],
        'Europe/Simferopol' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Simferopol'],
        'Europe/Sofia' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Sofia'],
        'Europe/Tallinn' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Tallinn'],
        'Europe/Tiraspol' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Tiraspol'],
        'Europe/Uzhgorod' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Uzhgorod'],
        'Europe/Vilnius' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Vilnius'],
        'Europe/Zaporozhye' => ['offset' => 'GMT+02:00', 'name' => 'Europe/Zaporozhye'],
        'Africa/Addis_Ababa' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Addis_Ababa'],
        'Africa/Asmara' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Asmara'],
        'Africa/Asmera' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Asmera'],
        'Africa/Dar_es_Salaam' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Dar_es_Salaam'],
        'Africa/Djibouti' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Djibouti'],
        'Africa/Kampala' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Kampala'],
        'Africa/Khartoum' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Khartoum'],
        'Africa/Mogadishu' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Mogadishu'],
        'Africa/Nairobi' => ['offset' => 'GMT+03:00', 'name' => 'Africa/Nairobi'],
        'Antarctica/Syowa' => ['offset' => 'GMT+03:00', 'name' => 'Antarctica/Syowa'],
        'Asia/Aden' => ['offset' => 'GMT+03:00', 'name' => 'Asia/Aden'],
        'Asia/Baghdad' => ['offset' => 'GMT+03:00', 'name' => 'Asia/Baghdad'],
        'Asia/Bahrain' => ['offset' => 'GMT+03:00', 'name' => 'Asia/Bahrain'],
        'Asia/Kuwait' => ['offset' => 'GMT+03:00', 'name' => 'Asia/Kuwait'],
        'Asia/Qatar' => ['offset' => 'GMT+03:00', 'name' => 'Asia/Qatar'],
        'Europe/Moscow' => ['offset' => 'GMT+03:00', 'name' => 'Europe/Moscow'],
        'Europe/Volgograd' => ['offset' => 'GMT+03:00', 'name' => 'Europe/Volgograd'],
        'Indian/Antananarivo' => ['offset' => 'GMT+03:00', 'name' => 'Indian/Antananarivo'],
        'Indian/Comoro' => ['offset' => 'GMT+03:00', 'name' => 'Indian/Comoro'],
        'Indian/Mayotte' => ['offset' => 'GMT+03:00', 'name' => 'Indian/Mayotte'],
        'Asia/Tehran' => ['offset' => 'GMT+03:30', 'name' => 'Asia/Tehran'],
        'Asia/Baku' => ['offset' => 'GMT+04:00', 'name' => 'Asia/Baku'],
        'Asia/Dubai' => ['offset' => 'GMT+04:00', 'name' => 'Asia/Dubai'],
        'Asia/Muscat' => ['offset' => 'GMT+04:00', 'name' => 'Asia/Muscat'],
        'Asia/Tbilisi' => ['offset' => 'GMT+04:00', 'name' => 'Asia/Tbilisi'],
        'Asia/Yerevan' => ['offset' => 'GMT+04:00', 'name' => 'Asia/Yerevan'],
        'Europe/Samara' => ['offset' => 'GMT+04:00', 'name' => 'Europe/Samara'],
        'Indian/Mahe' => ['offset' => 'GMT+04:00', 'name' => 'Indian/Mahe'],
        'Indian/Mauritius' => ['offset' => 'GMT+04:00', 'name' => 'Indian/Mauritius'],
        'Indian/Reunion' => ['offset' => 'GMT+04:00', 'name' => 'Indian/Reunion'],
        'Asia/Kabul' => ['offset' => 'GMT+04:30', 'name' => 'Asia/Kabul'],
        'Asia/Aqtau' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Aqtau'],
        'Asia/Aqtobe' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Aqtobe'],
        'Asia/Ashgabat' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Ashgabat'],
        'Asia/Ashkhabad' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Ashkhabad'],
        'Asia/Dushanbe' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Dushanbe'],
        'Asia/Karachi' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Karachi'],
        'Asia/Oral' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Oral'],
        'Asia/Samarkand' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Samarkand'],
        'Asia/Tashkent' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Tashkent'],
        'Asia/Yekaterinburg' => ['offset' => 'GMT+05:00', 'name' => 'Asia/Yekaterinburg'],
        'Indian/Kerguelen' => ['offset' => 'GMT+05:00', 'name' => 'Indian/Kerguelen'],
        'Indian/Maldives' => ['offset' => 'GMT+05:00', 'name' => 'Indian/Maldives'],
        'Asia/Calcutta' => ['offset' => 'GMT+05:30', 'name' => 'Asia/Calcutta'],
        'Asia/Colombo' => ['offset' => 'GMT+05:30', 'name' => 'Asia/Colombo'],
        'Asia/Kolkata' => ['offset' => 'GMT+05:30', 'name' => 'Asia/Kolkata'],
        'Asia/Katmandu' => ['offset' => 'GMT+05:45', 'name' => 'Asia/Katmandu'],
        'Antarctica/Mawson' => ['offset' => 'GMT+06:00', 'name' => 'Antarctica/Mawson'],
        'Antarctica/Vostok' => ['offset' => 'GMT+06:00', 'name' => 'Antarctica/Vostok'],
        'Asia/Almaty' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Almaty'],
        'Asia/Bishkek' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Bishkek'],
        'Asia/Dacca' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Dacca'],
        'Asia/Dhaka' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Dhaka'],
        'Asia/Novosibirsk' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Novosibirsk'],
        'Asia/Omsk' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Omsk'],
        'Asia/Qyzylorda' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Qyzylorda'],
        'Asia/Thimbu' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Thimbu'],
        'Asia/Thimphu' => ['offset' => 'GMT+06:00', 'name' => 'Asia/Thimphu'],
        'Indian/Chagos' => ['offset' => 'GMT+06:00', 'name' => 'Indian/Chagos'],
        'Asia/Rangoon' => ['offset' => 'GMT+06:30', 'name' => 'Asia/Rangoon'],
        'Indian/Cocos' => ['offset' => 'GMT+06:30', 'name' => 'Indian/Cocos'],
        'Antarctica/Davis' => ['offset' => 'GMT+07:00', 'name' => 'Antarctica/Davis'],
        'Asia/Bangkok' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Bangkok'],
        'Asia/Ho_Chi_Minh' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Ho_Chi_Minh'],
        'Asia/Hovd' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Hovd'],
        'Asia/Jakarta' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Jakarta'],
        'Asia/Krasnoyarsk' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Krasnoyarsk'],
        'Asia/Phnom_Penh' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Phnom_Penh'],
        'Asia/Pontianak' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Pontianak'],
        'Asia/Saigon' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Saigon'],
        'Asia/Vientiane' => ['offset' => 'GMT+07:00', 'name' => 'Asia/Vientiane'],
        'Indian/Christmas' => ['offset' => 'GMT+07:00', 'name' => 'Indian/Christmas'],
        'Antarctica/Casey' => ['offset' => 'GMT+08:00', 'name' => 'Antarctica/Casey'],
        'Asia/Brunei' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Brunei'],
        'Asia/Choibalsan' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Choibalsan'],
        'Asia/Chongqing' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Chongqing'],
        'Asia/Chungking' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Chungking'],
        'Asia/Harbin' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Harbin'],
        'Asia/Hong_Kong' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Hong_Kong'],
        'Asia/Irkutsk' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Irkutsk'],
        'Asia/Kashgar' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Kashgar'],
        'Asia/Kuala_Lumpur' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Kuala_Lumpur'],
        'Asia/Kuching' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Kuching'],
        'Asia/Macao' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Macao'],
        'Asia/Macau' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Macau'],
        'Asia/Makassar' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Makassar'],
        'Asia/Manila' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Manila'],
        'Asia/Shanghai' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Shanghai'],
        'Asia/Singapore' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Singapore'],
        'Asia/Taipei' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Taipei'],
        'Asia/Ujung_Pandang' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Ujung_Pandang'],
        'Asia/Ulaanbaatar' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Ulaanbaatar'],
        'Asia/Ulan_Bator' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Ulan_Bator'],
        'Asia/Urumqi' => ['offset' => 'GMT+08:00', 'name' => 'Asia/Urumqi'],
        'Australia/Perth' => ['offset' => 'GMT+08:00', 'name' => 'Australia/Perth'],
        'Australia/West' => ['offset' => 'GMT+08:00', 'name' => 'Australia/West'],
        'Australia/Eucla' => ['offset' => 'GMT+08:45', 'name' => 'Australia/Eucla'],
        'Asia/Dili' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Dili'],
        'Asia/Jayapura' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Jayapura'],
        'Asia/Pyongyang' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Pyongyang'],
        'Asia/Seoul' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Seoul'],
        'Asia/Tokyo' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Tokyo'],
        'Asia/Yakutsk' => ['offset' => 'GMT+09:00', 'name' => 'Asia/Yakutsk'],
        'Australia/Adelaide' => ['offset' => 'GMT+09:30', 'name' => 'Australia/Adelaide'],
        'Australia/Broken_Hill' => ['offset' => 'GMT+09:30', 'name' => 'Australia/Broken_Hill'],
        'Australia/Darwin' => ['offset' => 'GMT+09:30', 'name' => 'Australia/Darwin'],
        'Australia/North' => ['offset' => 'GMT+09:30', 'name' => 'Australia/North'],
        'Australia/South' => ['offset' => 'GMT+09:30', 'name' => 'Australia/South'],
        'Australia/Yancowinna' => ['offset' => 'GMT+09:30', 'name' => 'Australia/Yancowinna'],
        'Antarctica/DumontDUrville' => ['offset' => 'GMT+10:00', 'name' => 'Antarctica/DumontDUrville'],
        'Asia/Sakhalin' => ['offset' => 'GMT+10:00', 'name' => 'Asia/Sakhalin'],
        'Asia/Vladivostok' => ['offset' => 'GMT+10:00', 'name' => 'Asia/Vladivostok'],
        'Australia/ACT' => ['offset' => 'GMT+10:00', 'name' => 'Australia/ACT'],
        'Australia/Brisbane' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Brisbane'],
        'Australia/Canberra' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Canberra'],
        'Australia/Currie' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Currie'],
        'Australia/Hobart' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Hobart'],
        'Australia/Lindeman' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Lindeman'],
        'Australia/Melbourne' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Melbourne'],
        'Australia/NSW' => ['offset' => 'GMT+10:00', 'name' => 'Australia/NSW'],
        'Australia/Queensland' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Queensland'],
        'Australia/Sydney' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Sydney'],
        'Australia/Tasmania' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Tasmania'],
        'Australia/Victoria' => ['offset' => 'GMT+10:00', 'name' => 'Australia/Victoria'],
        'Australia/LHI' => ['offset' => 'GMT+10:30', 'name' => 'Australia/LHI'],
        'Australia/Lord_Howe' => ['offset' => 'GMT+10:30', 'name' => 'Australia/Lord_Howe'],
        'Asia/Magadan' => ['offset' => 'GMT+11:00', 'name' => 'Asia/Magadan'],
        'Antarctica/McMurdo' => ['offset' => 'GMT+12:00', 'name' => 'Antarctica/McMurdo'],
        'Antarctica/South_Pole' => ['offset' => 'GMT+12:00', 'name' => 'Antarctica/South_Pole'],
        'Asia/Anadyr' => ['offset' => 'GMT+12:00', 'name' => 'Asia/Anadyr'],
        'Asia/Kamchatka' => ['offset' => 'GMT+12:00', 'name' => 'Asia/Kamchatka'],
    ],

    'intervals' => [
        [
            'name' => 'Hourly',
            'value' => 'hourly',
        ],
        [
            'name' => 'Daily',
            'value' => 'daily',
        ],
        [
            'name' => 'Weekly',
            'value' => 'weekly',
        ],
        [
            'name' => 'Monthly',
            'value' => 'monthly',
        ],
        [
            'name' => 'Quarterly',
            'value' => 'quarterly',
        ],
        [
            'name' => 'Yearly',
            'value' => 'yearly',
        ],
        [
            'name' => 'Custom',
            'value' => 'cron',
        ],
    ],

    'minutes' => [
        '0' => ':00 (At the beginning of the hour.)',
        '5' => ':05',
        '10' => ':10',
        '15' => ':15 (At one quarter past the hour.)',
        '20' => ':20',
        '25' => ':25',
        '30' => ':30 (At half past the hour.)',
        '35' => ':35',
        '40' => ':40',
        '45' => ':45 (At one quarter until the hour.)',
        '50' => ':50',
        '55' => ':55',
        '*' => 'Every Minute',
        '*/5' => 'Every 5th Minute',
        '*/10' => 'Every 10th Minute',
        '*/15' => 'Every 15th Minute',
        '*/20' => 'Every 20th Minute',
        '0,30' => 'Every 1st & 30th Minute',
    ],

    'hours' => [
        '*' => 'Every Hour',
        '*/2' => 'Every Other Hour',
        '*/3' => 'Every Third Hour',
        '*/4' => 'Every Fourth Hour',
        '*/6' => 'Every Sixth Hour',
        '0,12' => 'Every Twelve Hour',
        '0' => '12:00 a.m.',
        '1' => '1:00 a.m.',
        '2' => '2:00 a.m.',
        '3' => '3:00 a.m.',
        '4' => '4:00 a.m.',
        '5' => '5:00 a.m.',
        '6' => '6:00 a.m.',
        '7' => '7:00 a.m.',
        '8' => '8:00 a.m.',
        '9' => '9:00 a.m.',
        '10' => '10:00 a.m.',
        '11' => '11:00 a.m.',
        '12' => '12:00 p.m.',
        '13' => '01:00 p.m.',
        '14' => '02:00 p.m.',
        '15' => '03:00 p.m.',
        '16' => '04:00 p.m.',
        '17' => '05:00 p.m.',
        '18' => '06:00 p.m.',
        '19' => '07:00 p.m.',
        '20' => '08:00 p.m.',
        '21' => '09:00 p.m.',
        '22' => '10:00 p.m.',
        '23' => '11:00 p.m.',
    ],

    'days' => [
        '*' => 'Every Day',
        //        '*/2' => 'Every Other Day',
        '1,15' => 'On the 1st and 15th of the Month',
        '1' => '1st',
        '2' => '2nd',
        '3' => '3rd',
        '4' => '4th',
        '5' => '5th',
        '6' => '6th',
        '7' => '7th',
        '8' => '8th',
        '9' => '9th',
        '10' => '10th',
        '11' => '11th',
        '12' => '12th',
        '13' => '13th',
        '14' => '14th',
        '15' => '15th',
        '16' => '16th',
        '17' => '17th',
        '18' => '18th',
        '19' => '19th',
        '20' => '20th',
        '21' => '21th',
        '22' => '22th',
        '23' => '23th',
        '24' => '24th',
        '25' => '25th',
        '26' => '26th',
        '27' => '27th',
        '28' => '28th',
        '29' => '29th',
        '30' => '30th',
        '31' => '31th',
    ],

    'months' => [
        '*' => 'Every Month',
        //        '*/2' => 'Every Other Month',
        //        '*/4' => 'Every Third Month',
        '1,7' => 'Every Six Months(Jan, July)',
        '1' => 'January',
        '2' => 'February',
        '3' => 'March',
        '4' => 'April',
        '5' => 'May',
        '6' => 'June',
        '7' => 'July',
        '8' => 'August',
        '9' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],

    'weekdays' => [
        '*' => 'Every Weekday',
        //        '1-5' => 'Every Weekday Day',
        //        '0,6' => 'Every Weekend Day',
        //        '1,3,5' => 'Every Monday, Wednesday, and Friday',
        //        '2,4' => 'Every Tuesday and Thursday',
        '0' => 'Sunday',
        '1' => 'Monday',
        '2' => 'Tuesday',
        '3' => 'Wednesday',
        '4' => 'Thursday',
        '5' => 'Friday',
        '6' => 'Saturday',
    ],

    'currency' => [

        'AED' => [
            'code' => 'AED',
            'name' => 'UAE Dirham',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'د.إ',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'AFN' => [
            'code' => 'AFN',
            'name' => 'Afghani',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '؋',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ALL' => [
            'code' => 'ALL',
            'name' => 'Lek',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'AMD' => [
            'code' => 'AMD',
            'name' => 'Armenian Dram',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'դր.',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ANG' => [
            'code' => 'ANG',
            'name' => 'Netherlands Antillean Guilder',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ƒ',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'AOA' => [
            'code' => 'AOA',
            'name' => 'Kwanza',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Kz',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ARS' => [
            'code' => 'ARS',
            'name' => 'Argentine Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ' ',
        ],

        'AWG' => [
            'code' => 'AWG',
            'name' => 'Aruban Florin',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ƒ',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'AZN' => [
            'code' => 'AZN',
            'name' => 'Azerbaijanian Manat',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₼',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BAM' => [
            'code' => 'BAM',
            'name' => 'Convertible Mark',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'КМ',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BBD' => [
            'code' => 'BBD',
            'name' => 'Barbados Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BDT' => [
            'code' => 'BDT',
            'name' => 'Taka',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '৳',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BGN' => [
            'code' => 'BGN',
            'name' => 'Bulgarian Lev',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'лв',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => ' ',
        ],

        'BHD' => [
            'code' => 'BHD',
            'name' => 'Bahraini Dinar',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'ب.د',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BIF' => [
            'code' => 'BIF',
            'name' => 'Burundi Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BMD' => [
            'code' => 'BMD',
            'name' => 'Bermudian Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BND' => [
            'code' => 'BND',
            'name' => 'Brunei Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BOB' => [
            'code' => 'BOB',
            'name' => 'Boliviano',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Bs.',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BOV' => [
            'code' => 'BOV',
            'name' => 'Mvdol',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Bs.',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BRL' => [
            'code' => 'BRL',
            'name' => 'Brazilian Real',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'R$',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'BSD' => [
            'code' => 'BSD',
            'name' => 'Bahamian Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BTN' => [
            'code' => 'BTN',
            'name' => 'Ngultrum',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Nu.',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BWP' => [
            'code' => 'BWP',
            'name' => 'Pula',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'P',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'BYN' => [
            'code' => 'BYN',
            'name' => 'Belarussian Ruble',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Br',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => ' ',
        ],

        'BZD' => [
            'code' => 'BZD',
            'name' => 'Belize Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CAD' => [
            'code' => 'CAD',
            'name' => 'Canadian Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CDF' => [
            'code' => 'CDF',
            'name' => 'Congolese Franc',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CHF' => [
            'code' => 'CHF',
            'name' => 'Swiss Franc',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'CHF',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CLF' => [
            'code' => 'CLF',
            'name' => 'Unidades de fomento',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'UF',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'CLP' => [
            'code' => 'CLP',
            'name' => 'Chilean Peso',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'CNY' => [
            'code' => 'CNY',
            'name' => 'Yuan Renminbi',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '¥',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'COP' => [
            'code' => 'COP',
            'name' => 'Colombian Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'CRC' => [
            'code' => 'CRC',
            'name' => 'Costa Rican Colon',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₡',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'CUC' => [
            'code' => 'CUC',
            'name' => 'Peso Convertible',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CUP' => [
            'code' => 'CUP',
            'name' => 'Cuban Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CVE' => [
            'code' => 'CVE',
            'name' => 'Cape Verde Escudo',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'CZK' => [
            'code' => 'CZK',
            'name' => 'Czech Koruna',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Kč',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'DJF' => [
            'code' => 'DJF',
            'name' => 'Djibouti Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fdj',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'DKK' => [
            'code' => 'DKK',
            'name' => 'Danish Krone',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'DOP' => [
            'code' => 'DOP',
            'name' => 'Dominican Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'DZD' => [
            'code' => 'DZD',
            'name' => 'Algerian Dinar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'د.ج',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'EGP' => [
            'code' => 'EGP',
            'name' => 'Egyptian Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ج.م',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ERN' => [
            'code' => 'ERN',
            'name' => 'Nakfa',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Nfk',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ETB' => [
            'code' => 'ETB',
            'name' => 'Ethiopian Birr',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Br',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '€',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'FJD' => [
            'code' => 'FJD',
            'name' => 'Fiji Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'FKP' => [
            'code' => 'FKP',
            'name' => 'Falkland Islands Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GBP' => [
            'code' => 'GBP',
            'name' => 'Pound Sterling',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GEL' => [
            'code' => 'GEL',
            'name' => 'Lari',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ლ',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GHS' => [
            'code' => 'GHS',
            'name' => 'Ghana Cedi',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₵',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GIP' => [
            'code' => 'GIP',
            'name' => 'Gibraltar Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GMD' => [
            'code' => 'GMD',
            'name' => 'Dalasi',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'D',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GNF' => [
            'code' => 'GNF',
            'name' => 'Guinea Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GTQ' => [
            'code' => 'GTQ',
            'name' => 'Quetzal',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Q',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'GYD' => [
            'code' => 'GYD',
            'name' => 'Guyana Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'HKD' => [
            'code' => 'HKD',
            'name' => 'Hong Kong Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'HNL' => [
            'code' => 'HNL',
            'name' => 'Lempira',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'HRK' => [
            'code' => 'HRK',
            'name' => 'Croatian Kuna',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'kn',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'HTG' => [
            'code' => 'HTG',
            'name' => 'Gourde',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'G',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'HUF' => [
            'code' => 'HUF',
            'name' => 'Forint',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Ft',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'IDR' => [
            'code' => 'IDR',
            'name' => 'Rupiah',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Rp',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'ILS' => [
            'code' => 'ILS',
            'name' => 'New Israeli Sheqel',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₪',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'INR' => [
            'code' => 'INR',
            'name' => 'Indian Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₹',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'IQD' => [
            'code' => 'IQD',
            'name' => 'Iraqi Dinar',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'ع.د',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'IRR' => [
            'code' => 'IRR',
            'name' => 'Iranian Rial',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '﷼',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ISK' => [
            'code' => 'ISK',
            'name' => 'Iceland Krona',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'kr',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'JMD' => [
            'code' => 'JMD',
            'name' => 'Jamaican Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'JOD' => [
            'code' => 'JOD',
            'name' => 'Jordanian Dinar',
            'precision' => 3,
            'subunit' => 100,
            'symbol' => 'د.ا',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'JPY' => [
            'code' => 'JPY',
            'name' => 'Yen',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => '¥',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KES' => [
            'code' => 'KES',
            'name' => 'Kenyan Shilling',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'KSh',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KGS' => [
            'code' => 'KGS',
            'name' => 'Som',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'som',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KHR' => [
            'code' => 'KHR',
            'name' => 'Riel',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '៛',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KMF' => [
            'code' => 'KMF',
            'name' => 'Comoro Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KPW' => [
            'code' => 'KPW',
            'name' => 'North Korean Won',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₩',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KRW' => [
            'code' => 'KRW',
            'name' => 'Won',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => '₩',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KWD' => [
            'code' => 'KWD',
            'name' => 'Kuwaiti Dinar',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'د.ك',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KYD' => [
            'code' => 'KYD',
            'name' => 'Cayman Islands Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'KZT' => [
            'code' => 'KZT',
            'name' => 'Tenge',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '〒',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LAK' => [
            'code' => 'LAK',
            'name' => 'Kip',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₭',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LBP' => [
            'code' => 'LBP',
            'name' => 'Lebanese Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ل.ل',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LKR' => [
            'code' => 'LKR',
            'name' => 'Sri Lanka Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LRD' => [
            'code' => 'LRD',
            'name' => 'Liberian Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LSL' => [
            'code' => 'LSL',
            'name' => 'Loti',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LTL' => [
            'code' => 'LTL',
            'name' => 'Lithuanian Litas',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Lt',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LVL' => [
            'code' => 'LVL',
            'name' => 'Latvian Lats',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Ls',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'LYD' => [
            'code' => 'LYD',
            'name' => 'Libyan Dinar',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'ل.د',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MAD' => [
            'code' => 'MAD',
            'name' => 'Moroccan Dirham',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'د.م.',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MDL' => [
            'code' => 'MDL',
            'name' => 'Moldovan Leu',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MGA' => [
            'code' => 'MGA',
            'name' => 'Malagasy Ariary',
            'precision' => 2,
            'subunit' => 5,
            'symbol' => 'Ar',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MKD' => [
            'code' => 'MKD',
            'name' => 'Denar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ден',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MMK' => [
            'code' => 'MMK',
            'name' => 'Kyat',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'K',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MNT' => [
            'code' => 'MNT',
            'name' => 'Tugrik',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₮',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MOP' => [
            'code' => 'MOP',
            'name' => 'Pataca',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'P',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MRO' => [
            'code' => 'MRO',
            'name' => 'Ouguiya',
            'precision' => 2,
            'subunit' => 5,
            'symbol' => 'UM',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MUR' => [
            'code' => 'MUR',
            'name' => 'Mauritius Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MVR' => [
            'code' => 'MVR',
            'name' => 'Rufiyaa',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'MVR',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MWK' => [
            'code' => 'MWK',
            'name' => 'Kwacha',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'MK',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MXN' => [
            'code' => 'MXN',
            'name' => 'Mexican Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MYR' => [
            'code' => 'MYR',
            'name' => 'Malaysian Ringgit',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'RM',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'MZN' => [
            'code' => 'MZN',
            'name' => 'Mozambique Metical',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'MTn',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'NAD' => [
            'code' => 'NAD',
            'name' => 'Namibia Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'NGN' => [
            'code' => 'NGN',
            'name' => 'Naira',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₦',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'NIO' => [
            'code' => 'NIO',
            'name' => 'Cordoba Oro',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'C$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'NOK' => [
            'code' => 'NOK',
            'name' => 'Norwegian Krone',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'NPR' => [
            'code' => 'NPR',
            'name' => 'Nepalese Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'OMR' => [
            'code' => 'OMR',
            'name' => 'Rial Omani',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'ر.ع.',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PAB' => [
            'code' => 'PAB',
            'name' => 'Balboa',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'B/.',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PEN' => [
            'code' => 'PEN',
            'name' => 'Sol',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'S/',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PGK' => [
            'code' => 'PGK',
            'name' => 'Kina',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'K',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PHP' => [
            'code' => 'PHP',
            'name' => 'Philippine Peso',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₱',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PKR' => [
            'code' => 'PKR',
            'name' => 'Pakistan Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'PLN' => [
            'code' => 'PLN',
            'name' => 'Zloty',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'zł',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => ' ',
        ],

        'PYG' => [
            'code' => 'PYG',
            'name' => 'Guarani',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => '₲',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'QAR' => [
            'code' => 'QAR',
            'name' => 'Qatari Rial',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ر.ق',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'RON' => [
            'code' => 'RON',
            'name' => 'New Romanian Leu',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Lei',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'RSD' => [
            'code' => 'RSD',
            'name' => 'Serbian Dinar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'РСД',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'RUB' => [
            'code' => 'RUB',
            'name' => 'Russian Ruble',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₽',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'RWF' => [
            'code' => 'RWF',
            'name' => 'Rwanda Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'FRw',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SAR' => [
            'code' => 'SAR',
            'name' => 'Saudi Riyal',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ر.س',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SBD' => [
            'code' => 'SBD',
            'name' => 'Solomon Islands Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SCR' => [
            'code' => 'SCR',
            'name' => 'Seychelles Rupee',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SDG' => [
            'code' => 'SDG',
            'name' => 'Sudanese Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SEK' => [
            'code' => 'SEK',
            'name' => 'Swedish Krona',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'decimal_mark' => ',',
            'thousands_separator' => ' ',
        ],

        'SGD' => [
            'code' => 'SGD',
            'name' => 'Singapore Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SHP' => [
            'code' => 'SHP',
            'name' => 'Saint Helena Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SLL' => [
            'code' => 'SLL',
            'name' => 'Leone',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Le',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SOS' => [
            'code' => 'SOS',
            'name' => 'Somali Shilling',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Sh',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SRD' => [
            'code' => 'SRD',
            'name' => 'Surinam Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SSP' => [
            'code' => 'SSP',
            'name' => 'South Sudanese Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'STD' => [
            'code' => 'STD',
            'name' => 'Dobra',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Db',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SVC' => [
            'code' => 'SVC',
            'name' => 'El Salvador Colon',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₡',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SYP' => [
            'code' => 'SYP',
            'name' => 'Syrian Pound',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '£S',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'SZL' => [
            'code' => 'SZL',
            'name' => 'Lilangeni',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'E',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'THB' => [
            'code' => 'THB',
            'name' => 'Baht',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '฿',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TJS' => [
            'code' => 'TJS',
            'name' => 'Somoni',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ЅМ',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TMT' => [
            'code' => 'TMT',
            'name' => 'Turkmenistan New Manat',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'T',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TND' => [
            'code' => 'TND',
            'name' => 'Tunisian Dinar',
            'precision' => 3,
            'subunit' => 1000,
            'symbol' => 'د.ت',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TOP' => [
            'code' => 'TOP',
            'name' => 'Pa’anga',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'T$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TRY' => [
            'code' => 'TRY',
            'name' => 'Turkish Lira',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₺',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'TTD' => [
            'code' => 'TTD',
            'name' => 'Trinidad and Tobago Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TWD' => [
            'code' => 'TWD',
            'name' => 'New Taiwan Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'TZS' => [
            'code' => 'TZS',
            'name' => 'Tanzanian Shilling',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Sh',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'UAH' => [
            'code' => 'UAH',
            'name' => 'Hryvnia',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '₴',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'UGX' => [
            'code' => 'UGX',
            'name' => 'Uganda Shilling',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'USh',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'UYU' => [
            'code' => 'UYU',
            'name' => 'Peso Uruguayo',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'UZS' => [
            'code' => 'UZS',
            'name' => 'Uzbekistan Sum',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'лв',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'VEF' => [
            'code' => 'VEF',
            'name' => 'Bolivar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'Bs F',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'VND' => [
            'code' => 'VND',
            'name' => 'Dong',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => '₫',
            'symbol_first' => true,
            'decimal_mark' => ',',
            'thousands_separator' => '.',
        ],

        'VUV' => [
            'code' => 'VUV',
            'name' => 'Vatu',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Vt',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'WST' => [
            'code' => 'WST',
            'name' => 'Tala',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'T',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XAG' => [
            'code' => 'XAG',
            'name' => 'Silver',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'oz t',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XAU' => [
            'code' => 'XAU',
            'name' => 'Gold',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'oz t',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XDR' => [
            'code' => 'XDR',
            'name' => 'SDR (Special Drawing Right)',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'SDR',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'XPF' => [
            'code' => 'XPF',
            'name' => 'CFP Franc',
            'precision' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'YER' => [
            'code' => 'YER',
            'name' => 'Yemeni Rial',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '﷼',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ZAR' => [
            'code' => 'ZAR',
            'name' => 'Rand',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'R',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ZMW' => [
            'code' => 'ZMW',
            'name' => 'Zambian Kwacha',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => 'ZK',
            'symbol_first' => false,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],

        'ZWL' => [
            'code' => 'ZWL',
            'name' => 'Zimbabwe Dollar',
            'precision' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'decimal_mark' => '.',
            'thousands_separator' => ',',
        ],
    ],

    'replacement_moment' => [
        'd' => 'DD',
        'D' => 'ddd',
        'j' => 'D',
        'l' => 'dddd',
        'N' => 'E',
        'S' => 'o',
        'w' => 'e',
        'z' => 'DDD',
        'W' => 'W',
        'F' => 'MMMM',
        'm' => 'MM',
        'M' => 'MMM',
        'n' => 'M',
        't' => '', // no equivalent
        'L' => '', // no equivalent
        'o' => 'YYYY',
        'Y' => 'YYYY',
        'y' => 'YY',
        'a' => 'a',
        'A' => 'A',
        'B' => '', // no equivalent
        'g' => 'h',
        'G' => 'H',
        'h' => 'hh',
        'H' => 'HH',
        'i' => 'mm',
        's' => 'ss',
        'u' => 'SSS',
        'e' => 'zz', // deprecated since version 1.6.0 of moment.js
        'I' => '', // no equivalent
        'O' => '', // no equivalent
        'P' => '', // no equivalent
        'T' => '', // no equivalent
        'Z' => '', // no equivalent
        'c' => '', // no equivalent
        'r' => '', // no equivalent
        'U' => 'X',
    ],
];
